version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: ti_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru

  app:
    build: .
    container_name: ti_enricher_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - VT_API_KEY=${VT_API_KEY}
      - ABUSEIPDB_API_KEY=${ABUSEIPDB_API_KEY}
      - OTX_API_KEY=${OTX_API_KEY}
      - VT_DELAY=15.0
      - ABUSEIPDB_DELAY=1.0
      - OTX_DELAY=0.5
    depends_on:
      - redis
    volumes:
      - ./reports:/app/reports

volumes:
  redis_data:
